### PR TITLE
Add podspec for CocoaPods

### PR DESCRIPTION
**Pull request by alexovits**

### CODE REVIEW

**Comment by saudahmed** [comment]
When will this change be merged

**Comment by saudahmed** [comment]
I am working on react native 0.60.4 and autolinking is not working for it because it says

!] use_native_modules! skipped the react-native dependency 'rn-apple-healthkit'. No podspec file was found.

**Comment by ty-sang** [comment]
Does owner still maintain this ? There are so many open PR, but I really do want this one merge in.

**Review by santi8194 — APPROVED** [review]

**Review by santi8194 — CHANGES_REQUESTED** [review]
A better approach would be to use package.json info.

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = package['name']
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = package['author']
  s.homepage     = package['homepage']
  s.platform     = :ios, "9.0"

  s.source       = { :git => "https://github.com/terrillo/rn-apple-healthkit", :tag => "master" }
  s.source_files  = "RCTAppleHealthKit/*.{h,m}"
  s.requires_arc = true

  s.dependency 'React'
end
```

**Review by JoelOnGithub — APPROVED** [review]

**Comment by tedcurrent** [comment]
Can we get this merged? Can't make a RN 0.61.1 release build without this fix.

**Comment by mifi** [comment]
Temporary fix for now:

add to Podfile:
```
  pod 'RCTAppleHealthKit', :podspec => '../RTCAppleHealthKit.podspec'
```

Create a file `RCTAppleHealthKit.podspec` in react native project root directory:
```
# https://github.com/terrillo/rn-apple-healthkit/pull/96

Pod::Spec.new do |s|
  s.name         = "RCTAppleHealthKit"
  s.version      = "0.6.5"
  s.summary      = "A React Native package for interacting with Apple HealthKit"
  s.license      = "MIT"
  s.homepage     = "https://github.com/terrillo/rn-apple-healthkit"
  s.authors      = "Terrillo Walls"
  s.platform     = :ios, "9.0"
  s.source       = { :git => "https://github.com/terrillo/rn-apple-healthkit.git", :tag => "0.6.5v" }
  s.source_files = "RCTAppleHealthKit/**/*.{h,m}"

  s.dependency "React"
end
```

**Pull request merged**
