### PR TITLE
Add TypeScript definition file

### PR DESCRIPTION
**Pull request by svbutko**

### CODE REVIEW

**Comment by EJohnF** [comment]
Nice idea to add this! Any plans for extending file for all available functions?

**Comment by svbutko** [comment]
> Nice idea to add this! Any plans for extending file for all available functions?

Yes, I'll add missing functions soon.

**Comment by Tobertet** [comment]
Please merge this, all typescript lovers will love you all.

**Comment by sanders-vag** [comment]
We need this as well, please merge!

**Comment by pie6k** [comment]
Would be great to have this merged.

**Comment by terrillo** [comment]
Hey everyone, I’ll take a look at this. Please keep in mind I don’t use TypeScript

**Comment by terrillo** [comment]
🎉

**Pull request merged**
