### PR TITLE
options to filter manually added informations / period flag to select the time interval / getDistanceSwimming

### PR DESCRIPTION
**Pull request by furyou81**
adding flags to the options object passed to getDailyStepCountSamples, getDailyDistanceWalkingRunningSamples, getDailyDistanceCyclingSamples, getDailyDistanceSwimmingSamples ... :
- includeManuallyAdded flag (true or false, by default false) => to decide if we want to get the information that were manually added by the user in the results
- period flag (number in minutes) => the time interval of the results (for example add period: 60 if we want to have the results displayed by hours)
- adding a function getDailyDistanceSwimmingSamples and a permission to get DistanceSwimming

### CODE REVIEW

**Comment by edgartrem** [comment]
I think you might also want to add a Documentation entry for `getDailyDistanceSwimmingSamples` in [Docs](https://github.com/terrillo/rn-apple-healthkit/tree/master/docs) and include it in  `README`

**Comment by furyou81** [comment]
you are right, I have added it in the docs and README.md

**Comment by EJohnF** [comment]
Nice work! Thanks)
But we got a problem that now it's two PR about skipping manual info, not sure so far what would be the best way for merging...
and I think `checkPermission` is redundant - there is authorisation check now

**Comment by furyou81** [comment]
Hi, welcome:) and sorry for taking so long to reply

Regarding skipping manual info, you can keep the PR that you prefer, if you prefer the other one I can just removed this part from mine, please let me know

Yes, you are right regarding checkPermission, I removed it

**Pull request merged**
